#!/bin/bash

# databases to compare
RIGHT=${1:-'climbing.db'}
LEFT=${2:-`dir backups/*.db -1t | head -n 1`}
echo ""
echo "Comparing $LEFT -> $RIGHT"
echo ""

# compare routes
echo ""
echo "Comparing Routes"
echo ""
colordiff <(sqlite3 $LEFT "SELECT * FROM Routes" ) <(sqlite3 $RIGHT "SELECT * FROM Routes")

# compare sends
echo ""
echo "Comparing Sends"
echo ""
colordiff <(sqlite3 $LEFT "SELECT * FROM Sends"  ) <(sqlite3 $RIGHT "SELECT * FROM Sends" )
echo ""
