#!/bin/bash

# generate send data javascript file
echo "data=$(./python/AutoREST.py climbing.db --dump-table=Sends)" > sends_vega/data.js

# send data to server
rsync -az --delete sends_vega root@darylstlaurent.com:/root/docker-server/static/
